// Code generated by mockery. DO NOT EDIT.

package freeport_mocks

import mock "github.com/stretchr/testify/mock"

// RetryOperation is an autogenerated mock type for the retryOperation type
type RetryOperation struct {
	mock.Mock
}

type RetryOperation_Expecter struct {
	mock *mock.Mock
}

func (_m *RetryOperation) EXPECT() *RetryOperation_Expecter {
	return &RetryOperation_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: port
func (_m *RetryOperation) Execute(port int) error {
	ret := _m.Called(port)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(port)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetryOperation_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RetryOperation_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - port int
func (_e *RetryOperation_Expecter) Execute(port interface{}) *RetryOperation_Execute_Call {
	return &RetryOperation_Execute_Call{Call: _e.mock.On("Execute", port)}
}

func (_c *RetryOperation_Execute_Call) Run(run func(port int)) *RetryOperation_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *RetryOperation_Execute_Call) Return(_a0 error) *RetryOperation_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryOperation_Execute_Call) RunAndReturn(run func(int) error) *RetryOperation_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewRetryOperation creates a new instance of RetryOperation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRetryOperation(t interface {
	mock.TestingT
	Cleanup(func())
}) *RetryOperation {
	mock := &RetryOperation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
